---
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch
spec:
  version: 7.12.1
  nodeSets:
  - name: default
    count: 3
    config:
      node.roles: [ master, data, ingest ]
      # This setting could have performance implications for production clusters.
      # See: https://www.elastic.co/guide/en/cloud-on-k8s/master/k8s-virtual-memory.html
      node.store.allow_mmap: false
      # https://www.elastic.co/guide/en/elasticsearch/reference/7.9/configuring-metricbeat.html
      xpack.monitoring.collection.enabled: true
      xpack.monitoring.elasticsearch.collection.enabled: false
    podTemplate:
      metadata:
        labels:
          stack-monitoring.elastic.co/type: es # to allow autodiscover by metricbeat
        annotations:
          co.elastic.logs/enabled: "true"
      spec:
        initContainers:
        - name: sysctl
          securityContext:
            privileged: true
          command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
        containers:
        - name: elasticsearch
          env:
          - name: ES_JAVA_OPTS
            value: -Xms500m -Xmx500m
          resources:
            requests:
              #cpu: 1 # no request means 0.1 by default (too little CPU)
              memory: 1Gi
            limits:
              memory: 1Gi
              cpu: 1
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 50Gi
---
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana
spec:
  version: 7.12.1
  count: 1
  http:
    service:
      spec:
        type: LoadBalancer
  elasticsearchRef:
    name: elasticsearch
  config:
    # https://www.elastic.co/guide/en/kibana/7.9/monitoring-metricbeat.html
    xpack.monitoring.kibana.collection.enabled: false
    xpack.monitoring.collection.enabled: true
  podTemplate:
    metadata:
      labels:
        stack-monitoring.elastic.co/type: kb # to allow autodiscover by metricbeat
      annotations:
        co.elastic.logs/enabled: "true"
    spec:
      containers:
      - name: kibana
        resources:
          requests:
            memory: 300M
          limits:
            memory: 1Gi
            cpu: 0.5