---
apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-configmap
data:
  logstash.yml: |
    http.host: "0.0.0.0"
    path.config: /usr/share/logstash/pipeline
    monitoring.enabled: false
    monitoring.cluster_uuid: changeme
  logstash.conf: |
    input {
      heartbeat {
        id => "heartbeat_input"
        message => "ok"
        interval => 60
      }
    }
    filter {
    }
    output {
      elasticsearch {
        hosts => ["https://elasticsearch-es-http.default.svc:9200"]
        user => "elastic"
        password => "changeme"
        index => "logstash-heartbeat-%{+YYYY.MM}"
        cacert => "/usr/share/logstash/config/certs/tls.crt"
        ssl_certificate_verification => false
      }
    }
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    monitoring_label_type: ls
  name: logstash-01
spec:
  containers:
  - image: docker.elastic.co/logstash/logstash:7.12.1
    name: logstash
    volumeMounts:
    - name: config-volume
      mountPath: /usr/share/logstash/config
    - name: logstash-pipeline-volume
      mountPath: /usr/share/logstash/pipeline
    - name: elasticsearch-ca
      readOnly: true
      mountPath: /usr/share/logstash/config/certs
  restartPolicy: OnFailure
  volumes:
  - name: config-volume
    configMap:
      name: logstash-configmap
      items:
        - key: logstash.yml
          path: logstash.yml
  - name: logstash-pipeline-volume
    configMap:
      name: logstash-configmap
      items:
        - key: logstash.conf
          path: logstash.conf
  - name: elasticsearch-ca
    secret:
      secretName: elasticsearch-es-http-ca-internal
      defaultMode: 420
      optional: false
status: {}
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    monitoring_label_type: ls
  name: logstash-02
spec:
  containers:
  - image: docker.elastic.co/logstash/logstash:7.10.1
    name: logstash2
    volumeMounts:
    - name: config-volume
      mountPath: /usr/share/logstash/config
    - name: logstash-pipeline-volume
      mountPath: /usr/share/logstash/pipeline
    - name: elasticsearch-ca
      readOnly: true
      mountPath: /usr/share/logstash/config/certs
  restartPolicy: OnFailure
  volumes:
  - name: config-volume
    configMap:
      name: logstash-configmap
      items:
        - key: logstash.yml
          path: logstash.yml
  - name: logstash-pipeline-volume
    configMap:
      name: logstash-configmap
      items:
        - key: logstash.conf
          path: logstash.conf
  - name: elasticsearch-ca
    secret:
      secretName: elasticsearch-es-http-ca-internal
      defaultMode: 420
      optional: false
status: {}
---